name: Test Test Orca IaC action

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  iac_scan_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Scan IaC
        uses: orcasecurity/shiftleft-iac-action@v1
        with:
          api_token:
            ${{ secrets.ORCA_SECURITY_API_TOKEN }}
          project_key:
            "default"
          path:
            "test"
          format:
            "sarif"
          output:
            "results/results.sarif"
      - name: Display sarif results
        if: always()
        run: |
          cat results/results.sarif
      - uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results/changed.sarif
